# Generated by Django 3.0.6 on 2020-05-21 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0002_order_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
    ]
