# Generated by Django 3.0.6 on 2020-05-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0003_remove_order_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='stock_count',
            field=models.IntegerField(default=0),
        ),
    ]
